CREATE TABLE data (
  id INT NOT NULL AUTO_INCREMENT,
  end_year INT,
  citylng DOUBLE,
  citylat DOUBLE,
  intensity VARCHAR(255),
  sector VARCHAR(255),
  topic VARCHAR(255),
  insight VARCHAR(255),
  swot VARCHAR(255),
  url VARCHAR(255),
  region VARCHAR(255),
  start_year INT,
  impact VARCHAR(255),
  added VARCHAR(255),
  published VARCHAR(255),
  city VARCHAR(255),
  country VARCHAR(255),
  relevance VARCHAR(255),
  pestle VARCHAR(255),
  source VARCHAR(255),
  title VARCHAR(255),
  likelihood VARCHAR(255),
  PRIMARY KEY (id)
);
